### ISSUE TITLE
Optimize pattern matching through use of dynamic constants

### ISSUE THREAD

**Issue by LifeIsStrange** [lampepfl/dotty-feature-requests#104]
Pattern matching support in Scala is a wonderful feature. But if my belief is true, it come at a cost:
Slower to far slower compile time, which is a big ergonomic and productivity cost for the developper, breaking it's mental *flow*.

Java ~15 is getting pattern matching support in switch, what a time to be alive!
Taking inspiration from their implementation would be wise from Dotty developers.
https://openjdk.java.net/jeps/8213076

The thing that trigerred my interest is this sentence:
*The implementation will likely make use of Dynamic Constants in the JVM.*
https://bugs.openjdk.java.net/browse/JDK-8177279

I have not the expertise to tell how much dynamic constant would improve the situation but I feel like they could be a real improvement.

What do you think?

**Comment by smarter** [comment]
I think we'll have to wait a while until this has been implemented end benchmarked. I also don't think we'll see any amazing speed-up (remember how Java used invokedynamic to implement lambda, which was supposed to allow new optimizations that were never actually implemented ?).
Closing because we don't really need an issue open to keep this in mind.
