### ISSUE TITLE
Provide scalc via the ToolProvider spi

### ISSUE THREAD

**Issue by bowbahdoe** [lampepfl/dotty-feature-requests#282]
https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/spi/ToolProvider.html

**Comment by ckipp01** [comment]
Since this is lacking some context, I'll go ahead and close since we're in the process of cleaning this repo up and archiving. @bowbahdoe if this is still relevant for you, please do open a discussion [here](https://github.com/lampepfl/dotty/discussions/new?category=feature-requests) with some more details.
